#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

SERVICES="hadoop-hdfs-datanode \
hadoop-hdfs-namenode"

if [ -z "${DIB_CDH_HDFS_ONLY:-}" ]; then
    SERVICES="$SERVICES cloudera-scm-agent \
cloudera-scm-server \
cloudera-scm-server-db \
hadoop-hdfs-secondarynamenode \
hadoop-mapreduce-historyserver \
hadoop-yarn-nodemanager \
hadoop-yarn-resourcemanager \
hive-metastore \
hive-server2 \
hive-webhcat-server \
hue \
oozie \
postgresql"

    if [ $DIB_CDH_VERSION != "5.0" ]; then
        SERVICES="$SERVICES impala-catalog \
impala-server \
impala-state-store \
solr-server \
spark-history-server"
    fi
fi

for i in $SERVICES
do
    if [ "$DISTRO_NAME" = "ubuntu" ]; then
        update-rc.d -f $i remove
    else
        chkconfig $i off
    fi
done
